# Generated by Django 4.1.7 on 2023-05-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sale_transaction_saleitem_amount_saleitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
            preserve_default=False,
        ),
    ]
