# Generated by Django 4.1.7 on 2023-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_sale_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='bill_type',
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
