# Generated by Django 4.1.7 on 2023-05-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_product_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='advance_amount',
            new_name='sale_amount',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='advance_amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='receive_amount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='receive_amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='vocuher_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_status',
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_sale_transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cash_sale_transaction', to='inventory.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='cogs_transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cogs_transaction', to='inventory.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='inventory_transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transaction', to='inventory.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='qty_in',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockpurchase',
            name='inventoy_transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventoy_transaction', to='inventory.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockpurchase',
            name='invoice_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockpurchase',
            name='miscellaneous_transaction',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='miscellaneous_transaction', to='inventory.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_stock', to='inventory.stock'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vocuher_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Sales', 'Sales'), ('Cash Payment', 'Cash Payment'), ('Bank Payment', 'Bank Payment'), ('Cash Receipt', 'Cash Receipt'), ('Bank Receipt', 'Bank Receipt')], max_length=50),
        ),
    ]
