# Generated by Django 4.1.7 on 2023-05-22 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_advance_amount_sale_sale_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='account_customer',
            field=models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, to='inventory.account'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='account_supplier',
            field=models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, to='inventory.account'),
        ),
        migrations.AlterField(
            model_name='stockpurchase',
            name='account',
            field=models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, to='inventory.account'),
        ),
    ]
