# Generated by Django 4.1.7 on 2023-05-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_sale_account_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockpurchase',
            old_name='inventoy_transaction',
            new_name='inventory_transaction',
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
