# Generated by Django 4.1.7 on 2023-05-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_inventoy_transaction_stockpurchase_inventory_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockpurchase',
            name='invoice_no',
            field=models.CharField(max_length=50),
        ),
    ]
