# Generated by Django 4.1.7 on 2023-05-25 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_sale_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='invoice_no',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
            preserve_default=False,
        ),
    ]
