# Generated by Django 4.1.7 on 2023-05-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_transaction_invoice_no_saleitem_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionorder',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactionorder',
            name='transaction_created',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactionorder', to='inventory.transactionorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionorder',
            name='vocuher_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Sales', 'Sales'), ('Cash Payment', 'Cash Payment'), ('Bank Payment', 'Bank Payment'), ('Cash Receipt', 'Cash Receipt'), ('Bank Receipt', 'Bank Receipt')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionorder',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactionorder',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
