# Generated by Django 4.1.7 on 2023-05-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_transactionorder_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpurchase',
            name='miscellaneous_transaction',
        ),
    ]
